### ISSUE TITLE
Suggestion to leave traits out of remaining amount of images

### ISSUE THREAD

**Issue by robbevrhst** [NotLuksus/nft-art-generator#11]
Hey, first of all thanks for the great project, I've been looking for something like this for a while!

**I have a suggestion for an improvement:**
It would be awesome if the sum of each used trait should not match the exact amount of images you try to make, but instead the trait should not be showed on the remaining amount / percentage of images.

**Example**
If I want to make 100 images and have 2 different hairstyles, I would like 50 to have hairstyle A, 25 of them should have hairstyle B and the remaining 25 should not have hair.

The only solution that I found for now is putting an empty png in the folder.

Thanks!

**Comment by NotLuksus** [comment]
Yes, the solution you have is the one that should be used, I will add that as a feature in a future release!
