### ISSUE TITLE
Not asking for "Split Metadatas"

### ISSUE THREAD

**Issue by Shimizu96** [NotLuksus/nft-art-generator#12]
When running the program it doesnt ask for "Do you want to split metadata files"

**Comment by james-ingold** [comment]
@Shimizu96 are you saying yes to the first question "Should metadata be generated?"
I wasn't able to reproduce this issue after saying yes to that question, let me know if there's any additional info that you can provide to help replicate the problem.

**Comment by octipus** [comment]
Can the script generate metadata in separate files? ie for 1.png -> 1.json file etc

**Comment by octipus** [comment]
at the moment metadata is packecd into 1 file for all images

**Comment by werksone** [comment]
Could this be updated to write out multiple metadata files? seems like that is going to be the most useful scenario.

**Comment by NotLuksus** [comment]
This feature is currently available on the Github. To install the development version clone the GitHub, go into the folder and install using `npm install -g .`

**Comment by octipus** [comment]
I can confirm the above works. However, on windows, i had to removed manually the npm package from `Users\username\AppData\Roaming\npm` then use `npm install -g --force` in the downloaded folder.
