### ISSUE TITLE
Traits grouped by value (e.g. colour)

### ISSUE THREAD

**Issue by thejoshsmith** [NotLuksus/nft-art-generator#15]
Hi there,

Just had a play with this piece of software and it's really awesome.

I was wondering if it's possible to group certain traits based on colour?

For example, if I had a character that could have a grey, blue or white body colour and an "Eyes" trait that could be grey, blue or white, is it possible to ensure that only blue eyes end up on blue bodies and white on white etc?

e.g.
```
images ---\
  Eyes --\
    TiredEyes --\
      BlueTiredEyes.png
      WhiteTiredEyes.png
      GreyTiredEyes.png
  BodyColour --\
    White.png
    Blue.png
    Grey.png
```

Let me know if this doesn't make sense and I will try explain in a better way 😂

**Comment by NotLuksus** [comment]
This currently is not supported, for a temporary solution you could probably combine the images with the body and use the completed image instead.
I hope that helps!
