### ISSUE TITLE
Error Generating Metadata

### ISSUE THREAD

**Issue by Aniconic** [NotLuksus/nft-art-generator#16]
The code works perfectly for generating the images I need, however, when it comes to generating the metadata it stops working. After all of the images are generated I receive long string of errors starting with `Error: Couldn't load image`
`(node:196704) UnhandledPromiseRejectionWarning: Error: Couldn't load image
    at img.onerror (C:\Users\user\AppData\Roaming\npm\node_modules\nft-art-generator\node_modules\merge-images\dist\index.umd.js:39:46)
    at setSource (C:\Users\user\AppData\Roaming\npm\node_modules\nft-art-generator\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\user\AppData\Roaming\npm\node_modules\nft-art-generator\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\user\AppData\Roaming\npm\node_modules\nft-art-generator\node_modules\merge-images\dist\index.umd.js:41:12
    at C:\Users\user\AppData\Roaming\npm\node_modules\nft-art-generator\node_modules\merge-images\dist\index.umd.js:30:55
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:196704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:196704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
If anyone could help me with this that'd be greatly appreciated.

**Comment by dcardines-design** [comment]
Anyone solved this problem?

**Comment by Aniconic** [comment]
> Anyone solved this problem?

Nobody has said anything about it yet

**Comment by dcardines-design** [comment]
@NotLuksus can you help with this brother?

**Comment by dcardines-design** [comment]
Solved it, it was just the count of traits, the totals of each trait group didn't match

**Comment by Aniconic** [comment]
> Solved it, it was just the count of traits, the totals of each trait group didn't match

Is that because I have an uneven number of traits?

**Comment by dcardines-design** [comment]
All of the traits should equal to a common total number:

Acc. to luksus

"The weights would need to look something like this
Folder 1: Red Background 12
Folder 2: Blue Sphere 5
                 Red Sphere 7
Folder 3: Propeller Hat 4
                 Cowboy Hat 5
                 Astronaut Helmet 3
                 
This results in the count of the entire folder 1 ,2 , 3 to 12 I hope that makes sense"

**Comment by Aniconic** [comment]
> All of the traits should equal to a common total number:
> 
> Acc. to luksus
> 
> "The weights would need to look something like this
> Folder 1: Red Background 12
> Folder 2: Blue Sphere 5
> Red Sphere 7
> Folder 3: Propeller Hat 4
> Cowboy Hat 5
> Astronaut Helmet 3
> 
> This results in the count of the entire folder 1 ,2 , 3 to 12 I hope that makes sense"

Oh so I need to have the number of assets in the title of the folder?

**Comment by NotLuksus** [comment]
The weights would need to look something like this
Folder 1: Red Background 12
Folder 2: Blue Sphere 5
Red Sphere 7
Folder 3: Propeller Hat 4
Cowboy Hat 5
Astronaut Helmet 3

This results in the count of the entire folder 1 ,2 , 3 to 12 I hope that makes sense

As said this is the correct solution to this.
The 2.0 version is in the works that will resolve that issues hopefully, but it will take some more time till its complete :)

**Comment by thommeredith** [comment]
Any update on v2.0?
