### ISSUE TITLE
NFTs generated are all off-centered/skewed

### ISSUE THREAD

**Issue by haaptics** [NotLuksus/nft-art-generator#19]
sorry - this is a pretty 'newbie' question; i was able to get a few NFTs generated using this, but all of the traits are off-centered.. is there any way to tweak this (either before the script runs or after the image is produced?)

Thanks

**Comment by NotLuksus** [comment]
You need to make sure your images fit directly.
So for example if you drop them into Photoshop or you image editing software of choice, all the images need to fit together without the need of them being adjusted.
