### ISSUE TITLE
Option to dump & read configuration to/from file

### ISSUE THREAD

**Issue by bbjay** [NotLuksus/nft-art-generator#3]
Great project! I had something similar in mind and was happy to find that this already exists.

As I was experimenting with a growing number of different traits, it became quite cumbersome to answer all the questions for settings, names & weights on each run.
While this interface is good for starters, i think an option to dump these information into a config-file, along with an option to skip the questions and instead read them from a config-file would be very helpful.

Would this be a feature you would want to merge? i could have a look into this...

**Comment by NotLuksus** [comment]
Sure, feel free to open a pull request.
Its really appreciated.
