### ISSUE TITLE
Problem with Canvas dependency at npm level

### ISSUE THREAD

**Issue by shemzz** [NotLuksus/nft-art-generator#36]
`npm install` failed on my machine. I did a little search and found it to be an issue with canvas dependency from **node modules**. what do you think I can do to get it working?

**Comment by smehrjerdian** [comment]
If you have an M1 chip you may experience this issue. I tried uninstalling VS Code and re-installing it via homebrew and then I ran this :

arch -arm64 brew install pkg-config cairo pango jpeg giflib librsvg

I can’t remember if there was anything else I did but below is an article of some different solutions you can try

lhttps://github.com/Automattic/node-canvas/issues/1733

**Comment by shemzz** [comment]
Thanks.. worked for me. Totally forgot to comment and close this issue.
