### ISSUE TITLE
nft-generate produces "command not found"

### ISSUE THREAD

**Issue by anhtz** [NotLuksus/nft-art-generator#4]
brew installed node, (v16.7.0, npm version is 7.20.3 running on macOS Big Sur 11.5.1

Tried running `sudo nft-generate` too and still said "command not found"

**Comment by MorpheusOfSteeze** [comment]
I am having this same issue

**Comment by anhtz** [comment]
I fixed mine up uninstalling NodeJS and npm and using `brew` to install both instead. After doing that it worked.
